### ISSUE TITLE
[BUG] picom background blur and notifications.

### ISSUE THREAD

**Issue by poiuedws** [manilarome/Glorious-Dotfiles#28]
after migrating the picom + panel type updates notifications look like this:
![image](https://user-images.githubusercontent.com/13078659/74449820-0af21980-4e75-11ea-953f-398c5607e5aa.png)
im assuming splash window type's background is being blured by picom.

possible fixes:
exclude blur from splash
blur the contents of the container, not the container itself, and draw text and such above it.

**Comment by manilarome** [comment]
> exclude blur from splash

```
blur-background-exclude = [
	"window_type = 'splash'",
];
```

> blur the contents of the container, not the container itself, and draw text and such above it.

I'm not sure if that's possible.

**Comment by manilarome** [comment]
Hello, yshui already fixed this issue. https://github.com/yshui/picom/issues/323.
