### ISSUE TITLE
[awesomewm] move widget configs to /configuration

### ISSUE THREAD

**Issue by ildar** [manilarome/Glorious-Dotfiles#31]
at least EMail and Weather widgets need it.

**Comment by manilarome** [comment]
> move widget configs to /configuration

I'm afraid that I'm not going to do that. Though in my local repo, I created a `secrets.lua` file that will store the credentials for email and weather widget and its in the configuration folder.

**Comment by ildar** [comment]
ok
Then what's the exact path for the values to reach from e.g.
configuration/init.lua or rc.lua ?

**Comment by manilarome** [comment]
Try this [one](https://drive.google.com/open?id=1Zy5P0UQEvngffp7InDUe8vuDKcliho2k), the dotfiles in this repo are really outdated.

**Comment by ildar** [comment]
Yes, this is the file layout I meant (almost). Though I'd prefer that ALL
the configuration-ish files be in /configuration/. Including rc.lua (with
root rc.lua being e.g. a mere symlink).
Consider my setup:
```
$  ls -l --full-time ~/.config/awesome/ | cut -c68-
binaries -> newconfig/binaries
configuration
layout -> newconfig/layout
module -> newconfig/module
newconfig -> /opt/Glorious-Dotfiles/config/awesome/GNawesOME
rc.lua -> configuration/rc.lua
theme -> newconfig/theme
widget -> newconfig/widget
```

**Comment by manilarome** [comment]
Uhm... that would be too complicated for other users like the beginners. I designed these configs to be a `plug 'n play` type of thing.

**Comment by ildar** [comment]
surely I didn't mean to propose this to mere users. But I wanted to
illustrate that configuration files are in /configuration, widgets are in
another folder etc.
Hope that in the end of the cycle you move widget secrets and settings to
/configuration. Thanks.

**Comment by manilarome** [comment]
Okay, thanks for the suggestion. I'll keep that in mind!
