### ISSUE TITLE
Naughty Notifications not working.

### ISSUE THREAD

**Issue by yigitcolakoglu** [manilarome/Glorious-Dotfiles#32]
(Sorry for broken english, I am not a native speaker)
Hello there, to begin with, I just love your rices, and especially floppy. I literally fell in love with it the moment I saw it on r/unixporn and you are the reason that I switched to awesome from i3. But even though I managed to get most of the theme and widgets to work, despite putting in lots of effort for a week, I couldn't manage to make the notifications and the notif-center work correctly. When I send a notification with "notify-send", it pops up on the top right corner as an ugly white and red box and the notification doesn't appear in the notification center. And I don't even get email notifications from the email widget. My lua knowledge is very limited but I managed to track down the issue to the `naughty.notify` calls in the widget files. Anything that calls to that function causes an assertion error. So I am pretty sure that there is something wrong with my configuration and not the theme files itself. I just can't figure out what the problem is. I will also attach the stderr of awesome below for more information:
`2020-03-02 23:13:02 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/awesome/lib/naughty/notification.lua:926: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/local/share/awesome/lib/naughty/core.lua:595: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:177: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/gears/object.lua:158: in function 'widget.ram.ram-meter.emit_signal'
	/usr/local/share/awesome/lib/naughty/notification.lua:1144: in function </usr/local/share/awesome/lib/naughty/notification.lua:1058>
	(...tail calls...)
	/home/yigit/.config/awesome/module/notifications.lua:83: in function </home/yigit/.config/awesome/module/notifications.lua:77>
	[C]: in ?
	[C]: in function 'assert'
	/usr/local/share/awesome/lib/naughty/notification.lua:926: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/local/share/awesome/lib/naughty/core.lua:595: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:177: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/gears/object.lua:158: in function 'widget.ram.ram-meter.emit_signal'
	/usr/local/share/awesome/lib/naughty/notification.lua:1144: in function </usr/local/share/awesome/lib/naughty/notification.lua:1058>
	(...tail calls...)
	/home/yigit/.config/awesome/widget/email/init.lua:172: in upvalue 'notify_new_email'
	/home/yigit/.config/awesome/widget/email/init.lua:212: in function </home/yigit/.config/awesome/widget/email/init.lua:206>
	(...tail calls...)
error: /usr/local/share/awesome/lib/naughty/notification.lua:926: assertion failed!
2020-03-02 23:13:02 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/awesome/lib/naughty/notification.lua:926: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/local/share/awesome/lib/naughty/core.lua:595: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:177: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/gears/object.lua:158: in function 'widget.ram.ram-meter.emit_signal'
	/usr/local/share/awesome/lib/naughty/notification.lua:1144: in function </usr/local/share/awesome/lib/naughty/notification.lua:1058>
	(...tail calls...)
	/home/yigit/.config/awesome/widget/email/init.lua:172: in upvalue 'notify_new_email'
	/home/yigit/.config/awesome/widget/email/init.lua:212: in function </home/yigit/.config/awesome/widget/email/init.lua:206>
	(...tail calls...)
error: /usr/local/share/awesome/lib/naughty/notification.lua:926: assertion failed!
2020-03-02 23:13:07 E: awesome: Error during a protected call: /usr/local/share/awesome/lib/naughty/notification.lua:926: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/awesome/lib/naughty/notification.lua:926: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/local/share/awesome/lib/naughty/core.lua:595: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:177: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/gears/object.lua:158: in function 'widget.ram.ram-meter.emit_signal'
	/usr/local/share/awesome/lib/naughty/notification.lua:1144: in function </usr/local/share/awesome/lib/naughty/notification.lua:1058>
	(...tail calls...)
	/home/yigit/.config/awesome/widget/wifi/init.lua:115: in upvalue 'notify_connection'
	/home/yigit/.config/awesome/widget/wifi/init.lua:146: in upvalue 'callback'
	/usr/local/share/awesome/lib/awful/widget/watch.lua:78: in function </usr/local/share/awesome/lib/awful/widget/watch.lua:77>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:487: in function </usr/local/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:601: in function </usr/local/share/awesome/lib/awful/spawn.lua:593>
[062 23:13:17.378380] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'
2020-03-02 23:13:51 W: awesome: awful: function spawn is deprecated, see awful.spawn.
stack traceback:
	/usr/local/share/awesome/lib/gears/debug.lua:107: in function 'gears.debug.deprecate'
	/usr/local/share/awesome/lib/awful/_compat.lua:17: in function 'awful.util.spawn'
	/home/yigit/.config/awesome/configuration/keys/global.lua:29: in field 'on_press'
	/usr/local/share/awesome/lib/awful/key.lua:258: in function </usr/local/share/awesome/lib/awful/key.lua:253>
[062 23:14:51.924734] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'
[062 23:14:52.502189] [PARSE ERROR] Unknown OSC code: 50
[062 23:36:51.203743] [PARSE ERROR] Unknown OSC code: 50
[062 23:36:51.973290] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '1'
[062 23:36:53.059338] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'
[062 23:36:54.433064] [PARSE ERROR] Unknown OSC code: 50
2020-03-02 23:37:45 E: awesome: Error during a protected call: ...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: attempt to index a nil value (field '?')
stack traceback:
	...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: in function <...yigit/.config/awesome/widget/music/mpd-music-updater.lua:194>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:487: in function </usr/local/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:601: in function </usr/local/share/awesome/lib/awful/spawn.lua:593>
[062 23:37:47.893373] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '1'
[062 23:37:48.521086] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'
[062 23:37:49.538357] [PARSE ERROR] Unknown OSC code: 50
2020-03-02 23:37:52 E: awesome: Error during a protected call: ...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: attempt to index a nil value (field '?')
stack traceback:
	...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: in function <...yigit/.config/awesome/widget/music/mpd-music-updater.lua:194>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:487: in function </usr/local/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:601: in function </usr/local/share/awesome/lib/awful/spawn.lua:593>
[062 23:37:54.478878] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '1'
[062 23:37:55.343917] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: '' and parameters: '0 2'
[062 23:37:56.420063] [PARSE ERROR] Unknown OSC code: 50
2020-03-02 23:37:59 E: awesome: Error during a protected call: ...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: attempt to index a nil value (field '?')
stack traceback:
	...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: in function <...yigit/.config/awesome/widget/music/mpd-music-updater.lua:194>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:487: in function </usr/local/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:601: in function </usr/local/share/awesome/lib/awful/spawn.lua:593>
2020-03-02 23:38:06 E: awesome: Error during a protected call: ...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: attempt to index a nil value (field '?')
stack traceback:
	...yigit/.config/awesome/widget/music/mpd-music-updater.lua:197: in function <...yigit/.config/awesome/widget/music/mpd-music-updater.lua:194>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:487: in function </usr/local/share/awesome/lib/awful/spawn.lua:481>
	[C]: in function 'xpcall'
	/usr/local/share/awesome/lib/gears/protected_call.lua:36: in function </usr/local/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
	/usr/local/share/awesome/lib/awful/spawn.lua:601: in function </usr/local/share/awesome/lib/awful/spawn.lua:593>
[062 23:38:07.991228] [PARSE ERROR] Unknown CSI code: 'm' with start_modifier: '>' and end_modifier: ';' and parameters: '1'`

**Comment by ppacher** [comment]
I'm on my phone and didn't check it but AFAIK some naughty/notification changes (especially rulesd) haven been merged into awesome master lately. Mabybe one of those changes broke it? Are you running ltest git master?

**Comment by manilarome** [comment]
@yigitcolakoglu  thanks for your kind words! @ppacher is right. The naughty library changes so fast in the master branch. @yigitcolakoglu The dotfiles here in my repo is outdated. Try this updated floppy setup [one](https://drive.google.com/file/d/1Zy5P0UQEvngffp7InDUe8vuDKcliho2k/view).

**Comment by yigitcolakoglu** [comment]
@manilarome will try it out once I get back to my laptop. Thanks :)

**Comment by yigitcolakoglu** [comment]
Hey @manilarome , I switched to the awesome config that you have linked and indeed, the notifications sent by the awesome config shows up on the top right. However, notifications that I send using `notify-send` only show a white notification box on the top right. I attached an image with a  notification below. Is it a bug or is the widget incapable of showing notifications by 'notif-send' because I think I read that it could here: https://github.com/manilarome/awesome-glorious-widgets/tree/master/notif-center

**Comment by manilarome** [comment]
Are you using the latest awesome-git master branch? Because `notify-send` works just fine here. 
![20200303_142303](https://user-images.githubusercontent.com/40349590/75748516-9d8e2600-5d5a-11ea-8bf7-d61a1ccdddc2.png)

**Comment by yigitcolakoglu** [comment]
Yep, I installed the awesome-git package from AUR. I can't find anything useful in the logs as well...

**Comment by manilarome** [comment]
Hmm that's weird. Are you using a compositor? I'm afraid I can't reproduce this. :|

**Comment by yigitcolakoglu** [comment]
Nope, İ have the exact same packages and the conf files that you have in the repo. But meh it is fine. Guess I will just have to deal with it :)

**Comment by manilarome** [comment]
I'm curious, can you please send a screenshot of the "white" notification? And try `notify-send`-ing on a vanilla rc.lua to check if it's still white.

**Comment by yigitcolakoglu** [comment]
There you go, 
![20200303_134233](https://user-images.githubusercontent.com/30830979/75768233-02468200-5d55-11ea-8603-39e97cc67c24.png)
And the result is still the same for a vanilla rc.lua

**Comment by manilarome** [comment]
Aha! It's the dunst! Try killing the dunst by `killall dunst` or by just uninstalling it.

**Comment by yigitcolakoglu** [comment]
God, I feel so dum right now. I though I knew a thing or two after using i3 for a year, but I guess not, lol... Anyways, sorry for bothering you, and thanks for all your help :)
